package setup.DEF;

import afs.nodes.def.*;
import afs.nodes.event.*;
import afs.nodes.expr.*;
import afs.nodes.prog.*;
import afs.nodes.stmt.*;
import afs.nodes.type.*;

import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;

/* The required start of a Coco/R grammar file. "Program" specifies the starting symbol of the grammar. */


public class Parser {
	public static final int _EOF = 0;
	public static final int _INT = 1;
	public static final int _DOUBLE = 2;
	public static final int _STRING = 3;
	public static final int _IDENT = 4;
	public static final int maxT = 56;

	static final boolean _T = true;
	static final boolean _x = false;
	static final int minErrDist = 2;

	public Token t;    // last recognized token
	public Token la;   // lookahead token
	int errDist = minErrDist;
	
	public Scanner scanner;
	public Errors errors;

	public DefNode mainNode = null; // This contains the AST generated by calling parser.Parse().

    public boolean hasErrors() {
        return errors.count > 0;
    }

    private DefNode toDefNode(List<DefNode> defs) {
        if (defs.isEmpty()) {
            throw new FatalError("Empty defs list");
        }
        DefNode left = defs.getFirst();

        if (defs.size() == 1) {
            return left;
        } else {
            int line = left.getLineNumber();
            int col = left.getColumnNumber();
            List<DefNode> rest = defs.subList(1, defs.size());
            DefNode right = toDefNode(rest);
            return switch(left) {
                case DefDeclarationNode defDeclarationNode -> new DefDeclarationNode(defDeclarationNode.getType(), defDeclarationNode.getIdentifier(), defDeclarationNode.getExpression(), right, line, col);
                case DefFunctionNode defFunctionNode -> new DefFunctionNode(defFunctionNode.getType(), defFunctionNode.getIdentifier(), defFunctionNode.getParameters(), defFunctionNode.getStatement(), right, line, col);
                case DefVisualizeNode defVisualizeNode -> {
                    throw new FatalError("Visualize node MUST be placed last");
                }
            };
        }
    }

    private EventNode toCompEvent(List<EventNode> events) {
        if (events.isEmpty()) {
            throw new FatalError("Empty events list");
        }
        EventNode left = events.getFirst();

        if (events.size() == 1) {
            return left;
        } else {
            int line = left.getLineNumber();
            int col = left.getColumnNumber();
            List<EventNode> rest = events.subList(1, events.size());
            EventNode right = toCompEvent(rest);
            return new EventCompositionNode(left, right, line, col);
        }
    }

    private StmtNode toCompStmt(List<StmtNode> stmts) {
        if (stmts.isEmpty()) {
            return new StmtSkipNode();
        }
        StmtNode left = stmts.getFirst();

        if (stmts.size() == 1) {
            return left;
        } else {
            int line = left.getLineNumber();
            int col = left.getColumnNumber();
            List<StmtNode> rest = stmts.subList(1, stmts.size());
            StmtNode right = toCompStmt(rest);
            if (left instanceof StmtDeclarationNode) {
                return new StmtDeclarationNode(((StmtDeclarationNode) left).getType(),
                                               ((StmtDeclarationNode) left).getIdentifier(),
                                               ((StmtDeclarationNode) left).getExpression(),
                                               right, line, col);
            } else {
                return new StmtCompositionNode(left, right, line, col);
            }
        }
    }

    private StmtNode declToCompStmt(List<StmtNode> stmts) {
        if (stmts.isEmpty()) {
            return new StmtSkipNode();
        }
        StmtNode left = stmts.getFirst();

        if (stmts.size() == 1) {
            return addReturnIfDeclaration(left);
        } else {
            int line = left.getLineNumber();
            int col = left.getColumnNumber();
            List<StmtNode> rest = stmts.subList(1, stmts.size());
            StmtNode right = declToCompStmt(rest);
            if (left instanceof StmtDeclarationNode) {
                return new StmtDeclarationNode(
                    ((StmtDeclarationNode) left).getType(),
                    ((StmtDeclarationNode) left).getIdentifier(),
                    ((StmtDeclarationNode) left).getExpression(),
                    right, line, col);
            } else {
                return new StmtCompositionNode(left, right, line, col);
            }
        }
    }
    private StmtNode addReturnIfDeclaration(StmtNode stmt) {
        if (stmt instanceof StmtDeclarationNode) {
            int line = stmt.getLineNumber();
            int col = stmt.getColumnNumber();
            ExprIdentifierNode ident = new ExprIdentifierNode(((StmtDeclarationNode) stmt).getIdentifier(), line, col);
            StmtReturnNode ret = new StmtReturnNode(ident, line, col);
            System.out.println("Inserting return statement for " + ident.getIdentifier());
            return new StmtDeclarationNode(((StmtDeclarationNode) stmt).getType(), ((StmtDeclarationNode) stmt).getIdentifier(), ((StmtDeclarationNode) stmt).getExpression(), ret, line, col);
        } else {
            return stmt;
        }
    }

    private ExprNode makeUnOpExpr(List<Character> unaries, ExprNode base, int line, int col) {
        ExprNode result = base;
        int index = 0;
        while (index < unaries.size()) {
            char ch = unaries.get(index);
            result = switch (ch) {
                case '!' -> new ExprUnopNode(result, UnOp.NOT, line, col);
                case '-' -> new ExprUnopNode(result, UnOp.NEG, line, col);
                default -> throw new FatalError("Unknown unary operator: " + ch);
            };
            index++;
        }
        return result;
    }

    private ExprNode makeBinOpExpr(ExprNode left, String op, ExprNode right, int line, int column) {
        return switch (op) {
            case "*" -> new ExprBinopNode(left, BinOp.MUL, right, line, column);
            case "/" -> new ExprBinopNode(left, BinOp.DIV, right, line, column);
            case "+" -> new ExprBinopNode(left, BinOp.ADD, right, line, column);
            case "-" -> new ExprBinopNode(left, BinOp.SUB, right, line, column);
            case "++" -> new ExprBinopNode(left, BinOp.CONCAT, right, line, column);
            case "<=" -> {  ExprNode equals = makeBinOpExpr(left, "==", right, line, column);
                            ExprNode lessThan = makeBinOpExpr(left, "<", right, line, column);
                            yield makeBinOpExpr(equals, "||", lessThan, line, column);
            }
            case ">=" -> {  ExprNode equals = makeBinOpExpr(left, "==", right, line, column);
                            ExprNode lessThan = makeBinOpExpr(left, ">", right, line, column);
                            yield makeBinOpExpr(equals, "||", lessThan, line, column);
            }
            case "<" -> new ExprBinopNode(left, BinOp.LT, right, line, column);
            case ">" -> new ExprBinopNode(right, BinOp.LT, left, line, column);
            case "==" -> new ExprBinopNode(left, BinOp.EQ, right, line, column);
            case "!=" -> {  ExprNode equal = makeBinOpExpr(left, "==", right, line, column);
                            yield new ExprUnopNode(equal, UnOp.NOT, line, column);
            }
            case "&&" -> new ExprBinopNode(left, BinOp.AND, right, line, column);
            case "||" -> {  ExprNode notLeftExpr = new ExprUnopNode(left, UnOp.NOT, line, column);
                            ExprNode notRightExpr = new ExprUnopNode(right, UnOp.NOT, line, column);
                            ExprNode andNode = makeBinOpExpr(notLeftExpr, "&&", notRightExpr, line, column);
                            yield new ExprUnopNode(andNode, UnOp.NOT, line, column);
            }
            default -> throw new FatalError("Unknown binary operator: " + op);
        };
    }

/*------------------------------------------------------------------------*/
/* The following section contains the token specification of AFS.*/


	public Parser(Scanner scanner) {
		this.scanner = scanner;
		errors = new Errors();
	}

	void SynErr (int n) {
		if (errDist >= minErrDist) errors.SynErr(la.line, la.col, n);
		errDist = 0;
	}

	public void SemErr (String msg) {
		if (errDist >= minErrDist) errors.SemErr(t.line, t.col, msg);
		errDist = 0;
	}
	
	void Get () {
		for (;;) {
			t = la;
			la = scanner.Scan();
			if (la.kind <= maxT) {
				++errDist;
				break;
			}

			la = t;
		}
	}
	
	void Expect (int n) {
		if (la.kind==n) Get(); else { SynErr(n); }
	}
	
	boolean StartOf (int s) {
		return set[s][la.kind];
	}
	
	void ExpectWeak (int n, int follow) {
		if (la.kind == n) Get();
		else {
			SynErr(n);
			while (!StartOf(follow)) Get();
		}
	}
	
	boolean WeakSeparator (int n, int syFol, int repFol) {
		int kind = la.kind;
		if (kind == n) { Get(); return true; }
		else if (StartOf(repFol)) return false;
		else {
			SynErr(n);
			while (!(set[syFol][kind] || set[repFol][kind] || set[0][kind])) {
				Get();
				kind = la.kind;
			}
			return StartOf(syFol);
		}
	}
	
	void Program() {
		mainNode = Def();
	}

	DefNode  Def() {
		DefNode  def;
		def = null; List<DefNode> defs = new ArrayList<>(); 
		while (!(StartOf(1))) {SynErr(57); Get();}
		if (la.kind == 5) {
			def = FnDef();
		} else if (la.kind == 9) {
			def = ImgDef();
		} else if (StartOf(2)) {
			def = VarDef();
		} else SynErr(58);
		defs.add(def); 
		while (StartOf(3)) {
			if (la.kind == 5) {
				def = FnDef();
			} else if (la.kind == 9) {
				def = ImgDef();
			} else {
				def = VarDef();
			}
			defs.add(def); 
		}
		def = Visualize();
		defs.add(def); def = toDefNode(defs); 
		return def;
	}

	DefNode  FnDef() {
		DefNode  func;
		List<Param> params = new ArrayList<>(); 
		Expect(5);
		TypeNode type = FunctionType();
		Expect(4);
		int line = t.line; int col = t.col; String ident = t.val; 
		Expect(6);
		if (StartOf(2)) {
			Param param = Param();
			params.add(param); 
			while (la.kind == 7) {
				Get();
				param = Param();
				params.add(param); 
			}
		}
		Expect(8);
		StmtNode stmt = StmtBlock();
		func = new DefFunctionNode(type, ident, params, stmt, null, line, col); 
		return func;
	}

	DefNode  ImgDef() {
		DefNode  img;
		List<Param> params = new ArrayList<>(); 
		Expect(9);
		Expect(4);
		int line = t.line; int col = t.col; String ident = t.val; 
		Expect(6);
		if (StartOf(2)) {
			Param param = Param();
			params.add(param); 
			while (la.kind == 7) {
				Get();
				param = Param();
				params.add(param); 
			}
		}
		Expect(8);
		StmtNode decl = DeclBlock();
		img = new DefFunctionNode(new TypeShapeNode(line, col), ident, params, decl, null, line, col); 
		return img;
	}

	DefNode  VarDef() {
		DefNode  var;
		TypeNode type = Type();
		Expect(4);
		int line = t.line; int col = t.col; String ident = t.val; 
		Expect(10);
		ExprNode expr = Expr();
		Expect(11);
		var = new DefDeclarationNode(type, ident, expr, null, line, col); 
		return var;
	}

	DefNode  Visualize() {
		DefNode  vis;
		List<ExprNode> arguments = new ArrayList<>(); 
		Expect(12);
		int line = t.line; int col = t.col; 
		Expect(4);
		String ident = t.val; 
		Expect(6);
		if (StartOf(4)) {
			ExprNode arg = Expr();
			arguments.add(arg); 
			while (la.kind == 7) {
				Get();
				arg = Expr();
				arguments.add(arg); 
			}
		}
		Expect(8);
		Expect(13);
		EventNode event = Events();
		vis = new DefVisualizeNode(ident, arguments, event, line, col); 
		return vis;
	}

	TypeNode  FunctionType() {
		TypeNode  type;
		type = null; 
		if (la.kind == 51) {
			Get();
			type = new TypeVoidNode(t.line, t.col); 
		} else if (StartOf(2)) {
			type = Type();
		} else SynErr(59);
		return type;
	}

	Param  Param() {
		Param  param;
		TypeNode type = Type();
		Expect(4);
		int line = t.line; int col = t.col; String ident = t.val; 
		param = new Param(type, ident, line, col); 
		return param;
	}

	StmtNode  StmtBlock() {
		StmtNode  stmt;
		List<StmtNode> stmts = new ArrayList<>(); 
		Expect(15);
		while (StartOf(5)) {
			StmtNode innerStmt = Stmt();
			stmts.add(innerStmt); 
		}
		Expect(16);
		stmt = toCompStmt(stmts); 
		return stmt;
	}

	StmtNode  DeclBlock() {
		StmtNode  stmt;
		List<StmtNode> decls = new ArrayList<>(); 
		Expect(15);
		while (StartOf(6)) {
			StmtNode decl = Decl();
			decls.add(decl); 
		}
		Expect(16);
		stmt = declToCompStmt(decls); 
		return stmt;
	}

	TypeNode  Type() {
		TypeNode  type;
		type = null; 
		if (la.kind == 52) {
			Get();
			type = new TypeIntNode(t.line, t.col); 
		} else if (la.kind == 53) {
			Get();
			type = new TypeDoubleNode(t.line, t.col); 
		} else if (la.kind == 54) {
			Get();
			type = new TypeBoolNode(t.line, t.col); 
		} else if (la.kind == 55) {
			Get();
			type = new TypeStringNode(t.line, t.col); 
		} else if (la.kind == 17) {
			Get();
			TypeNode innerType = Type();
			Expect(18);
			type = new TypeListNode(innerType, t.line, t.col); 
		} else SynErr(60);
		return type;
	}

	ExprNode  Expr() {
		ExprNode  expr;
		expr = AndExpr();
		while (la.kind == 34) {
			Get();
			String op = t.val; int line = t.line; int col = t.col; 
			ExprNode right = AndExpr();
			expr = makeBinOpExpr(expr, op, right, line, col); 
		}
		return expr;
	}

	EventNode  Events() {
		EventNode  event;
		List<EventNode> events = new ArrayList<>(); List<ExprNode> arguments = new ArrayList<>(); String ident, fname; 
		Expect(4);
		ident = t.val; 
		Expect(14);
		Expect(4);
		int line = t.line; int col = t.col; fname = t.val; 
		Expect(6);
		if (StartOf(4)) {
			ExprNode arg = Expr();
			arguments.add(arg); 
			while (la.kind == 7) {
				Get();
				arg = Expr();
				arguments.add(arg); 
			}
		}
		Expect(8);
		Expect(11);
		event = new EventDeclarationNode(ident, fname, arguments, line, col); events.add(event); 
		while (la.kind == 14) {
			line = t.line; col = t.col; arguments = new ArrayList<>(); 
			Get();
			Expect(4);
			line = t.line; col = t.col; ident = t.val; 
			Expect(6);
			if (StartOf(4)) {
				ExprNode arg = Expr();
				arguments.add(arg); 
				while (la.kind == 7) {
					Get();
					arg = Expr();
					arguments.add(arg); 
				}
			}
			Expect(8);
			Expect(11);
			event = new EventDeclarationNode(ident, fname, arguments, line, col); events.add(event); 
		}
		event = toCompEvent(events); 
		return event;
	}

	StmtNode  Stmt() {
		StmtNode  stmt;
		stmt = new StmtSkipNode(); 
		if (StartOf(2)) {
			stmt = StmtDeclaration();
		} else if (la.kind == 19) {
			stmt = StmtIf();
		} else if (la.kind == 22) {
			stmt = StmtWhile();
		} else if (la.kind == 23) {
			stmt = StmtReturn();
		} else if (la.kind == 4) {
			Get();
			int line = t.line; int col = t.col; String ident = t.val; 
			if (la.kind == 10) {
				stmt = StmtAssignment(ident, line, col);
			} else if (la.kind == 17) {
				stmt = StmtListAssignment(ident, line, col);
			} else if (la.kind == 6) {
				stmt = StmtFuncCall(ident, line, col);
			} else SynErr(61);
		} else SynErr(62);
		return stmt;
	}

	StmtNode  StmtDeclaration() {
		StmtNode  stmt;
		TypeNode type = Type();
		Expect(4);
		int line = t.line; int col = t.col; String ident = t.val; 
		Expect(10);
		ExprNode expr = Expr();
		stmt = new StmtDeclarationNode(type, ident, expr, new StmtSkipNode(), line, col); 
		Expect(11);
		return stmt;
	}

	StmtNode  StmtIf() {
		StmtNode  stmt;
		while (!(la.kind == 0 || la.kind == 19)) {SynErr(63); Get();}
		Expect(19);
		int line = t.line; int col = t.col; 
		Expect(6);
		ExprNode expr = Expr();
		Expect(8);
		Expect(20);
		StmtNode thenStmt = StmtBlock();
		stmt = new StmtIfNode(expr, thenStmt, new StmtSkipNode(), line, col); 
		if (la.kind == 21) {
			Get();
			StmtNode elseStmt = StmtBlock();
			stmt = new StmtIfNode(expr, thenStmt, elseStmt, line, col); 
		}
		return stmt;
	}

	StmtNode  StmtWhile() {
		StmtNode  stmt;
		while (!(la.kind == 0 || la.kind == 22)) {SynErr(64); Get();}
		Expect(22);
		int line = t.line; int col = t.col; 
		Expect(6);
		ExprNode expr = Expr();
		Expect(8);
		Expect(14);
		StmtNode whlStmt = StmtBlock();
		stmt = new StmtWhileNode(expr, whlStmt, line, col); 
		return stmt;
	}

	StmtNode  StmtReturn() {
		StmtNode  stmt;
		Expect(23);
		int line = t.line; int col = t.col; 
		ExprNode expr = Expr();
		stmt = new StmtReturnNode(expr, line, col); 
		Expect(11);
		return stmt;
	}

	StmtNode  StmtAssignment(String ident, int line, int col) {
		StmtNode  stmt;
		Expect(10);
		ExprNode expr = Expr();
		stmt = new StmtAssignmentNode(ident, expr, line, col); 
		Expect(11);
		return stmt;
	}

	StmtNode  StmtListAssignment(String ident, int line, int col) {
		StmtNode  stmt;
		List<ExprNode> exprList = new ArrayList<>(); 
		Expect(17);
		ExprNode expr = Expr();
		exprList.add(expr); 
		Expect(18);
		while (la.kind == 17) {
			Get();
			expr = Expr();
			exprList.add(expr); 
			Expect(18);
		}
		Expect(10);
		expr = Expr();
		stmt = new StmtListAssignmentNode(ident, exprList, expr, line, col); 
		Expect(11);
		return stmt;
	}

	StmtNode  StmtFuncCall(String ident, int line, int col) {
		StmtNode  stmt;
		List<ExprNode> arguments = new ArrayList<>(); 
		Expect(6);
		if (StartOf(4)) {
			ExprNode arg = Expr();
			arguments.add(arg); 
			while (la.kind == 7) {
				Get();
				arg = Expr();
				arguments.add(arg); 
			}
		}
		Expect(8);
		Expect(11);
		stmt = new StmtFunctionCallNode(ident, arguments, t.line, t.col); 
		return stmt;
	}

	StmtNode  Decl() {
		StmtNode  decl;
		decl = new StmtSkipNode(); 
		if (StartOf(7)) {
			decl = DeclDecl();
		} else if (la.kind == 19) {
			decl = DeclIf();
		} else if (StartOf(8)) {
			ExprNode expr = DeclExpr();
			Expect(11);
			decl = new StmtReturnNode(expr, t.line, t.col); 
		} else SynErr(65);
		return decl;
	}

	StmtNode  DeclDecl() {
		StmtNode  decl;
		ExprNode declExpr = null; 
		TypeNode type = DeclType();
		Expect(4);
		int line = t.line; int col = t.col; String ident = t.val; 
		Expect(10);
		if (StartOf(8)) {
			declExpr = DeclExpr();
		} else if (StartOf(4)) {
			declExpr = Expr();
		} else SynErr(66);
		decl = new StmtDeclarationNode(type, ident, declExpr, null, line, col); 
		Expect(11);
		return decl;
	}

	StmtNode  DeclIf() {
		StmtNode  decl;
		while (!(la.kind == 0 || la.kind == 19)) {SynErr(67); Get();}
		Expect(19);
		int line = t.line; int col = t.col; 
		Expect(6);
		ExprNode expr = Expr();
		Expect(8);
		Expect(20);
		StmtNode thenDecl = DeclBlock();
		decl = new StmtIfNode(expr, thenDecl, new StmtSkipNode(), line, col); 
		if (la.kind == 21) {
			Get();
			StmtNode elseDecl = DeclBlock();
			decl = new StmtIfNode(expr, thenDecl, elseDecl, line, col); 
		}
		return decl;
	}

	ExprNode  DeclExpr() {
		ExprNode  declExpr;
		declExpr = null; 
		switch (la.kind) {
		case 24: {
			declExpr = Text();
			break;
		}
		case 25: {
			declExpr = Line();
			break;
		}
		case 27: {
			declExpr = Curve();
			break;
		}
		case 28: {
			declExpr = Place();
			break;
		}
		case 30: {
			declExpr = Scale();
			break;
		}
		case 32: {
			declExpr = Rotate();
			break;
		}
		default: SynErr(68); break;
		}
		return declExpr;
	}

	TypeNode  DeclType() {
		TypeNode  type;
		type = null; 
		if (la.kind == 50) {
			Get();
			type = new TypeShapeNode(t.line, t.col); 
		} else if (StartOf(2)) {
			type = Type();
		} else SynErr(69);
		return type;
	}

	ExprNode  Text() {
		ExprNode  declExpr;
		Expect(24);
		int line = t.line; int col = t.col; 
		ExprNode expr = Expr();
		declExpr = new ExprTextNode(expr, line, col); 
		return declExpr;
	}

	ExprNode  Line() {
		ExprNode  declExpr;
		List<ExprNode> exprList = new ArrayList<>(); 
		Expect(25);
		int line = t.line; int col = t.col; 
		Expect(6);
		ExprNode expr = Expr();
		exprList.add(expr); 
		Expect(7);
		expr = Expr();
		exprList.add(expr); 
		Expect(8);
		Expect(26);
		Expect(6);
		expr = Expr();
		exprList.add(expr); 
		Expect(7);
		expr = Expr();
		exprList.add(expr); 
		Expect(8);
		while (la.kind == 26) {
			Get();
			Expect(6);
			expr = Expr();
			exprList.add(expr); 
			Expect(7);
			expr = Expr();
			exprList.add(expr); 
			Expect(8);
		}
		declExpr = new ExprLineNode(exprList, line, col); 
		return declExpr;
	}

	ExprNode  Curve() {
		ExprNode  declExpr;
		List<ExprNode> exprList = new ArrayList<>(); 
		Expect(27);
		int line = t.line; int col = t.col; 
		Expect(6);
		ExprNode expr = Expr();
		exprList.add(expr); 
		Expect(7);
		expr = Expr();
		exprList.add(expr); 
		Expect(8);
		Expect(26);
		Expect(6);
		expr = Expr();
		exprList.add(expr); 
		Expect(7);
		expr = Expr();
		exprList.add(expr); 
		Expect(8);
		Expect(26);
		Expect(6);
		expr = Expr();
		exprList.add(expr); 
		Expect(7);
		expr = Expr();
		exprList.add(expr); 
		Expect(8);
		while (la.kind == 26) {
			Get();
			Expect(6);
			expr = Expr();
			exprList.add(expr); 
			Expect(7);
			expr = Expr();
			exprList.add(expr); 
			Expect(8);
			Expect(26);
			Expect(6);
			expr = Expr();
			exprList.add(expr); 
			Expect(7);
			expr = Expr();
			exprList.add(expr); 
			Expect(8);
		}
		declExpr = new ExprCurveNode(exprList, line, col); 
		return declExpr;
	}

	ExprNode  Place() {
		ExprNode  declExpr;
		Expect(28);
		int line = t.line; int col = t.col; 
		ExprNode lExpr = Expr();
		Expect(29);
		Expect(6);
		ExprNode mExpr = Expr();
		Expect(7);
		ExprNode rExpr = Expr();
		Expect(8);
		declExpr = new ExprPlaceNode(lExpr, mExpr, rExpr, line, col); 
		return declExpr;
	}

	ExprNode  Scale() {
		ExprNode  declExpr;
		Expect(30);
		int line = t.line; int col = t.col; 
		ExprNode lExpr = Expr();
		Expect(31);
		Expect(6);
		ExprNode mExpr = Expr();
		Expect(7);
		ExprNode rExpr = Expr();
		Expect(7);
		Expect(8);
		declExpr = new ExprScaleNode(lExpr, mExpr, rExpr, line, col); 
		return declExpr;
	}

	ExprNode  Rotate() {
		ExprNode  declExpr;
		Expect(32);
		int line = t.line; int col = t.col; 
		ExprNode fExpr = Expr();
		Expect(33);
		Expect(6);
		ExprNode sExpr = Expr();
		Expect(7);
		ExprNode tExpr = Expr();
		Expect(8);
		Expect(31);
		ExprNode lExpr = Expr();
		declExpr = new ExprRotateNode(fExpr, sExpr, tExpr, lExpr, line, col); 
		return declExpr;
	}

	ExprNode  AndExpr() {
		ExprNode  expr;
		expr = EqExpr();
		while (la.kind == 35) {
			Get();
			String op = t.val; int line = t.line; int col = t.col; 
			ExprNode right = EqExpr();
			expr = makeBinOpExpr(expr, op, right, line, col); 
		}
		return expr;
	}

	ExprNode  EqExpr() {
		ExprNode  expr;
		expr = RelExpr();
		while (la.kind == 36 || la.kind == 37) {
			if (la.kind == 36) {
				Get();
			} else {
				Get();
			}
			String op = t.val; int line = t.line; int col = t.col; 
			ExprNode right = RelExpr();
			expr = makeBinOpExpr(expr, op, right, line, col); 
		}
		return expr;
	}

	ExprNode  RelExpr() {
		ExprNode  expr;
		expr = ConcatExpr();
		while (StartOf(9)) {
			if (la.kind == 38) {
				Get();
			} else if (la.kind == 39) {
				Get();
			} else if (la.kind == 40) {
				Get();
			} else {
				Get();
			}
			String op = t.val; int line = t.line; int col = t.col; 
			ExprNode right = ConcatExpr();
			expr = makeBinOpExpr(expr, op, right, line, col); 
		}
		return expr;
	}

	ExprNode  ConcatExpr() {
		ExprNode  expr;
		expr = PlusExpr();
		while (la.kind == 42) {
			Get();
			String op = t.val; int line = t.line; int col = t.col; 
			ExprNode right = PlusExpr();
			expr = makeBinOpExpr(expr, op, right, line, col); 
		}
		return expr;
	}

	ExprNode  PlusExpr() {
		ExprNode  expr;
		expr = MultExpr();
		while (la.kind == 43 || la.kind == 44) {
			if (la.kind == 43) {
				Get();
			} else {
				Get();
			}
			String op = t.val; int line = t.line; int col = t.col; 
			ExprNode right = MultExpr();
			expr = makeBinOpExpr(expr, op, right, line, col); 
		}
		return expr;
	}

	ExprNode  MultExpr() {
		ExprNode  expr;
		expr = NotExpr();
		while (la.kind == 45 || la.kind == 46) {
			if (la.kind == 45) {
				Get();
			} else {
				Get();
			}
			String op = t.val; int line = t.line; int col = t.col; 
			ExprNode right = NotExpr();
			expr = makeBinOpExpr(expr, op, right, line, col); 
		}
		return expr;
	}

	ExprNode  NotExpr() {
		ExprNode  expr;
		List<Character> unaries = new ArrayList(); int line = -1; int col = -1; 
		while (la.kind == 44 || la.kind == 47) {
			if (la.kind == 47) {
				Get();
				unaries.add('!'); 
			} else {
				Get();
				unaries.add('-'); 
			}
			line = t.line; col = t.col; 
		}
		expr = Term();
		expr = makeUnOpExpr(unaries, expr, line, col);  
		return expr;
	}

	ExprNode  Term() {
		ExprNode  expr;
		expr = null; 
		switch (la.kind) {
		case 4: {
			Get();
			String ident = t.val; int line = t.line; int col = t.col; 
			expr = new ExprIdentifierNode(ident, line, col); 
			if (la.kind == 6 || la.kind == 17) {
				if (la.kind == 17) {
					expr = ExprListAccess(ident, line, col);
				} else {
					expr = ExprFuncCall(ident, line, col);
				}
			}
			break;
		}
		case 17: {
			expr = ExprListDeclaration();
			break;
		}
		case 1: {
			Get();
			expr = new ExprIntNode(t.val, t.line, t.col); 
			break;
		}
		case 2: {
			Get();
			expr = new ExprDoubleNode(t.val, t.line, t.col); 
			break;
		}
		case 3: {
			Get();
			expr = new ExprStringNode(t.val, t.line, t.col); 
			break;
		}
		case 48: case 49: {
			if (la.kind == 48) {
				Get();
			} else {
				Get();
			}
			expr = new ExprBoolNode(t.val, t.line, t.col); 
			break;
		}
		case 6: {
			Get();
			expr = Expr();
			Expect(8);
			break;
		}
		default: SynErr(70); break;
		}
		return expr;
	}

	ExprNode  ExprListAccess(String ident, int line, int col) {
		ExprNode  expr;
		List<ExprNode> exprList = new ArrayList<>(); 
		Expect(17);
		expr = Expr();
		exprList.add(expr); 
		Expect(18);
		while (la.kind == 17) {
			Get();
			expr = Expr();
			exprList.add(expr); 
			Expect(18);
		}
		expr = new ExprListAccessNode(ident, exprList, line, col); 
		return expr;
	}

	ExprFunctionCallNode  ExprFuncCall(String ident, int line, int col) {
		ExprFunctionCallNode  funcCall;
		List<ExprNode> exprList = new ArrayList<>(); 
		Expect(6);
		if (StartOf(4)) {
			ExprNode arg = Expr();
			exprList.add(arg); 
			while (la.kind == 7) {
				Get();
				arg = Expr();
				exprList.add(arg); 
			}
		}
		Expect(8);
		funcCall = new ExprFunctionCallNode(ident, exprList, line, col); 
		return funcCall;
	}

	ExprNode  ExprListDeclaration() {
		ExprNode  expr;
		List<ExprNode> exprs = new ArrayList<>(); 
		Expect(17);
		int line = t.line; int col = t.col; 
		if (StartOf(4)) {
			expr = Expr();
			exprs.add(expr); 
		}
		while (la.kind == 7) {
			Get();
			expr = Expr();
			exprs.add(expr); 
		}
		Expect(18);
		expr = new ExprListDeclaration(exprs, line, col); 
		return expr;
	}



	public void Parse() {
		la = new Token();
		la.val = "";		
		Get();
		Program();
		Expect(0);

		scanner.buffer.Close();
	}

	private static final boolean[][] set = {
		{_T,_x,_x,_x, _x,_T,_x,_x, _x,_T,_x,_x, _x,_x,_x,_x, _x,_T,_x,_T, _x,_x,_T,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _T,_T,_T,_T, _x,_x},
		{_T,_x,_x,_x, _x,_T,_x,_x, _x,_T,_x,_x, _x,_x,_x,_x, _x,_T,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _T,_T,_T,_T, _x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_T,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _T,_T,_T,_T, _x,_x},
		{_x,_x,_x,_x, _x,_T,_x,_x, _x,_T,_x,_x, _x,_x,_x,_x, _x,_T,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _T,_T,_T,_T, _x,_x},
		{_x,_T,_T,_T, _T,_x,_T,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_T,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _T,_x,_x,_T, _T,_T,_x,_x, _x,_x,_x,_x, _x,_x},
		{_x,_x,_x,_x, _T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_T,_x,_T, _x,_x,_T,_T, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _T,_T,_T,_T, _x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_T,_x,_T, _x,_x,_x,_x, _T,_T,_x,_T, _T,_x,_T,_x, _T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_T,_x, _T,_T,_T,_T, _x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_T,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_T,_x, _T,_T,_T,_T, _x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _T,_T,_x,_T, _T,_x,_T,_x, _T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_T,_T, _T,_T,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x}

	};
} // end Parser


class Errors {
	public int count = 0;                                    // number of errors detected
	public java.io.PrintStream errorStream = System.out;     // error messages go to this stream
	public String errMsgFormat = "-- line {0} col {1}: {2}"; // 0=line, 1=column, 2=text
	
	protected void printMsg(int line, int column, String msg) {
		StringBuffer b = new StringBuffer(errMsgFormat);
		int pos = b.indexOf("{0}");
		if (pos >= 0) { b.delete(pos, pos+3); b.insert(pos, line); }
		pos = b.indexOf("{1}");
		if (pos >= 0) { b.delete(pos, pos+3); b.insert(pos, column); }
		pos = b.indexOf("{2}");
		if (pos >= 0) b.replace(pos, pos+3, msg);
		errorStream.println(b.toString());
	}
	
	public void SynErr (int line, int col, int n) {
		String s;
		switch (n) {
			case 0: s = "EOF expected"; break;
			case 1: s = "INT expected"; break;
			case 2: s = "DOUBLE expected"; break;
			case 3: s = "STRING expected"; break;
			case 4: s = "IDENT expected"; break;
			case 5: s = "\"fn\" expected"; break;
			case 6: s = "\"(\" expected"; break;
			case 7: s = "\",\" expected"; break;
			case 8: s = "\")\" expected"; break;
			case 9: s = "\"img\" expected"; break;
			case 10: s = "\"=\" expected"; break;
			case 11: s = "\";\" expected"; break;
			case 12: s = "\"visualize\" expected"; break;
			case 13: s = "\":\" expected"; break;
			case 14: s = "\"do\" expected"; break;
			case 15: s = "\"{\" expected"; break;
			case 16: s = "\"}\" expected"; break;
			case 17: s = "\"[\" expected"; break;
			case 18: s = "\"]\" expected"; break;
			case 19: s = "\"if\" expected"; break;
			case 20: s = "\"then\" expected"; break;
			case 21: s = "\"else\" expected"; break;
			case 22: s = "\"while\" expected"; break;
			case 23: s = "\"return\" expected"; break;
			case 24: s = "\"text\" expected"; break;
			case 25: s = "\"line\" expected"; break;
			case 26: s = "\"to\" expected"; break;
			case 27: s = "\"curve\" expected"; break;
			case 28: s = "\"place\" expected"; break;
			case 29: s = "\"at\" expected"; break;
			case 30: s = "\"scale\" expected"; break;
			case 31: s = "\"by\" expected"; break;
			case 32: s = "\"rotate\" expected"; break;
			case 33: s = "\"around\" expected"; break;
			case 34: s = "\"||\" expected"; break;
			case 35: s = "\"&&\" expected"; break;
			case 36: s = "\"==\" expected"; break;
			case 37: s = "\"!=\" expected"; break;
			case 38: s = "\"<=\" expected"; break;
			case 39: s = "\"<\" expected"; break;
			case 40: s = "\">=\" expected"; break;
			case 41: s = "\">\" expected"; break;
			case 42: s = "\"++\" expected"; break;
			case 43: s = "\"+\" expected"; break;
			case 44: s = "\"-\" expected"; break;
			case 45: s = "\"*\" expected"; break;
			case 46: s = "\"/\" expected"; break;
			case 47: s = "\"!\" expected"; break;
			case 48: s = "\"true\" expected"; break;
			case 49: s = "\"false\" expected"; break;
			case 50: s = "\"shape\" expected"; break;
			case 51: s = "\"void\" expected"; break;
			case 52: s = "\"int\" expected"; break;
			case 53: s = "\"double\" expected"; break;
			case 54: s = "\"bool\" expected"; break;
			case 55: s = "\"string\" expected"; break;
			case 56: s = "??? expected"; break;
			case 57: s = "this symbol not expected in Def"; break;
			case 58: s = "invalid Def"; break;
			case 59: s = "invalid FunctionType"; break;
			case 60: s = "invalid Type"; break;
			case 61: s = "invalid Stmt"; break;
			case 62: s = "invalid Stmt"; break;
			case 63: s = "this symbol not expected in StmtIf"; break;
			case 64: s = "this symbol not expected in StmtWhile"; break;
			case 65: s = "invalid Decl"; break;
			case 66: s = "invalid DeclDecl"; break;
			case 67: s = "this symbol not expected in DeclIf"; break;
			case 68: s = "invalid DeclExpr"; break;
			case 69: s = "invalid DeclType"; break;
			case 70: s = "invalid Term"; break;
			default: s = "error " + n; break;
		}
		printMsg(line, col, s);
		count++;
	}

	public void SemErr (int line, int col, String s) {	
		printMsg(line, col, s);
		count++;
	}
	
	public void SemErr (String s) {
		errorStream.println(s);
		count++;
	}
	
	public void Warning (int line, int col, String s) {	
		printMsg(line, col, s);
	}
	
	public void Warning (String s) {
		errorStream.println(s);
	}
} // Errors


class FatalError extends RuntimeException {
	public static final long serialVersionUID = 1L;
	public FatalError(String s) { super(s); }
}
