package setup.STMTBLOCK;

import afs.nodes.expr.*;
import afs.nodes.stmt.*;
import afs.nodes.type.*;

import java.util.ArrayList;
import java.util.List;

/* The required start of a Coco/R grammar file. "Program" specifies the starting symbol of the grammar. */


public class Parser {
	public static final int _EOF = 0;
	public static final int _INT = 1;
	public static final int _DOUBLE = 2;
	public static final int _STRING = 3;
	public static final int _IDENT = 4;
	public static final int maxT = 42;

	static final boolean _T = true;
	static final boolean _x = false;
	static final int minErrDist = 2;

	public Token t;    // last recognized token
	public Token la;   // lookahead token
	int errDist = minErrDist;
	
	public Scanner scanner;
	public Errors errors;

	public StmtNode mainNode = null; // This contains the AST generated by calling parser.Parse().

public boolean hasErrors() {
return errors.count > 0;
}

private StmtNode toCompStmt(List<StmtNode> stmts) {
if (stmts.isEmpty()) {
return new StmtSkipNode();
}
StmtNode left = stmts.getFirst();

if (stmts.size() == 1) {
return left;
} else {
int line = left.getLineNumber();
int col = left.getColumnNumber();
List<StmtNode> rest = stmts.subList(1, stmts.size());
StmtNode right = toCompStmt(rest);
if (left instanceof StmtDeclarationNode) {
return new StmtDeclarationNode(((StmtDeclarationNode) left).getType(),
((StmtDeclarationNode) left).getIdentifier(),
((StmtDeclarationNode) left).getExpression(),
right, line, col);
} else {
return new StmtCompositionNode(left, right, line, col);
}
}
}

private ExprNode makeUnOpExpr(List<Character> unaries, ExprNode base, int line, int col) {
ExprNode result = base;
int index = 0;
while (index < unaries.size()) {
char ch = unaries.get(index);
result = switch (ch) {
case '!' -> new ExprUnopNode(result, UnOp.NOT, line, col);
case '-' -> new ExprUnopNode(result, UnOp.NEG, line, col);
default -> throw new RuntimeException("Unknown unary operator: " + ch);
};
index++;
}
return result;
}

private ExprNode makeBinOpExpr(ExprNode left, String op, ExprNode right, int line, int column) {
return switch (op) {
case "*" -> new ExprBinopNode(left, BinOp.MUL, right, line, column);
case "/" -> new ExprBinopNode(left, BinOp.DIV, right, line, column);
case "+" -> new ExprBinopNode(left, BinOp.ADD, right, line, column);
case "-" -> new ExprBinopNode(left, BinOp.SUB, right, line, column);
case "++" -> new ExprBinopNode(left, BinOp.CONCAT, right, line, column);
case "<=" -> {  ExprNode equals = makeBinOpExpr(left, "==", right, line, column);
ExprNode lessThan = makeBinOpExpr(left, "<", right, line, column);
yield makeBinOpExpr(equals, "||", lessThan, line, column);
}
case ">=" -> {  ExprNode equals = makeBinOpExpr(left, "==", right, line, column);
ExprNode lessThan = makeBinOpExpr(left, ">", right, line, column);
yield makeBinOpExpr(equals, "||", lessThan, line, column);
}
case "<" -> new ExprBinopNode(left, BinOp.LT, right, line, column);
case ">" -> new ExprBinopNode(right, BinOp.LT, left, line, column);
case "==" -> new ExprBinopNode(left, BinOp.EQ, right, line, column);
case "!=" -> {  ExprNode equal = makeBinOpExpr(left, "==", right, line, column);
yield new ExprUnopNode(equal, UnOp.NOT, line, column);
}
case "&&" -> new ExprBinopNode(left, BinOp.AND, right, line, column);
case "||" -> {  ExprNode notLeftExpr = new ExprUnopNode(left, UnOp.NOT, line, column);
ExprNode notRightExpr = new ExprUnopNode(right, UnOp.NOT, line, column);
ExprNode andNode = makeBinOpExpr(notLeftExpr, "&&", notRightExpr, line, column);
yield new ExprUnopNode(andNode, UnOp.NOT, line, column);
}
default -> throw new RuntimeException("Unknown binary operator: " + op);
};
}

/*------------------------------------------------------------------------*/
/* The following section contains the token specification of AFS.*/


	public Parser(Scanner scanner) {
		this.scanner = scanner;
		errors = new Errors();
	}

	void SynErr (int n) {
		if (errDist >= minErrDist) errors.SynErr(la.line, la.col, n);
		errDist = 0;
	}

	public void SemErr (String msg) {
		if (errDist >= minErrDist) errors.SemErr(t.line, t.col, msg);
		errDist = 0;
	}
	
	void Get () {
		for (;;) {
			t = la;
			la = scanner.Scan();
			if (la.kind <= maxT) {
				++errDist;
				break;
			}

			la = t;
		}
	}
	
	void Expect (int n) {
		if (la.kind==n) Get(); else { SynErr(n); }
	}
	
	boolean StartOf (int s) {
		return set[s][la.kind];
	}
	
	void ExpectWeak (int n, int follow) {
		if (la.kind == n) Get();
		else {
			SynErr(n);
			while (!StartOf(follow)) Get();
		}
	}
	
	boolean WeakSeparator (int n, int syFol, int repFol) {
		int kind = la.kind;
		if (kind == n) { Get(); return true; }
		else if (StartOf(repFol)) return false;
		else {
			SynErr(n);
			while (!(set[syFol][kind] || set[repFol][kind] || set[0][kind])) {
				Get();
				kind = la.kind;
			}
			return StartOf(syFol);
		}
	}
	
	void Program() {
		mainNode = StmtBlock();
	}

	StmtNode  StmtBlock() {
		StmtNode  stmt;
		List<StmtNode> stmts = new ArrayList<>(); 
		Expect(5);
		while (StartOf(1)) {
			StmtNode innerStmt = Stmt();
			stmts.add(innerStmt); 
		}
		Expect(6);
		stmt = toCompStmt(stmts); 
		return stmt;
	}

	StmtNode  Stmt() {
		StmtNode  stmt;
		stmt = new StmtSkipNode(); 
		if (StartOf(2)) {
			stmt = StmtDeclaration();
		} else if (la.kind == 11) {
			stmt = StmtIf();
		} else if (la.kind == 16) {
			stmt = StmtWhile();
		} else if (la.kind == 18) {
			stmt = StmtReturn();
		} else if (la.kind == 4) {
			Get();
			int line = t.line; int col = t.col; String ident = t.val; 
			if (la.kind == 7) {
				stmt = StmtAssignment(ident, line, col);
			} else if (la.kind == 9) {
				stmt = StmtListAssignment(ident, line, col);
			} else if (la.kind == 12) {
				stmt = StmtFuncCall(ident, line, col);
			} else SynErr(43);
		} else SynErr(44);
		return stmt;
	}

	StmtNode  StmtDeclaration() {
		StmtNode  stmt;
		TypeNode type = Type();
		Expect(4);
		int line = t.line; int col = t.col; String ident = t.val; 
		Expect(7);
		ExprNode expr = Expr();
		stmt = new StmtDeclarationNode(type, ident, expr, new StmtSkipNode(), line, col); 
		Expect(8);
		return stmt;
	}

	StmtNode  StmtIf() {
		StmtNode  stmt;
		while (!(la.kind == 0 || la.kind == 11)) {SynErr(45); Get();}
		Expect(11);
		int line = t.line; int col = t.col; 
		Expect(12);
		ExprNode expr = Expr();
		Expect(13);
		Expect(14);
		StmtNode thenStmt = StmtBlock();
		stmt = new StmtIfNode(expr, thenStmt, new StmtSkipNode(), line, col); 
		if (la.kind == 15) {
			Get();
			StmtNode elseStmt = StmtBlock();
			stmt = new StmtIfNode(expr, thenStmt, elseStmt, line, col); 
		}
		return stmt;
	}

	StmtNode  StmtWhile() {
		StmtNode  stmt;
		while (!(la.kind == 0 || la.kind == 16)) {SynErr(46); Get();}
		Expect(16);
		int line = t.line; int col = t.col; 
		Expect(12);
		ExprNode expr = Expr();
		Expect(13);
		Expect(17);
		StmtNode whlStmt = StmtBlock();
		stmt = new StmtWhileNode(expr, whlStmt, line, col); 
		return stmt;
	}

	StmtNode  StmtReturn() {
		StmtNode  stmt;
		Expect(18);
		int line = t.line; int col = t.col; 
		ExprNode expr = Expr();
		stmt = new StmtReturnNode(expr, line, col); 
		Expect(8);
		return stmt;
	}

	StmtNode  StmtAssignment(String ident, int line, int col) {
		StmtNode  stmt;
		Expect(7);
		ExprNode expr = Expr();
		stmt = new StmtAssignmentNode(ident, expr, line, col); 
		Expect(8);
		return stmt;
	}

	StmtNode  StmtListAssignment(String ident, int line, int col) {
		StmtNode  stmt;
		List<ExprNode> exprList = new ArrayList<>(); 
		Expect(9);
		ExprNode expr = Expr();
		exprList.add(expr); 
		Expect(10);
		while (la.kind == 9) {
			Get();
			expr = Expr();
			exprList.add(expr); 
			Expect(10);
		}
		Expect(7);
		expr = Expr();
		stmt = new StmtListAssignmentNode(ident, exprList, expr, line, col); 
		Expect(8);
		return stmt;
	}

	StmtNode  StmtFuncCall(String ident, int line, int col) {
		StmtNode  stmt;
		List<ExprNode> arguments = new ArrayList<>(); 
		Expect(12);
		if (StartOf(3)) {
			ExprNode arg = Expr();
			arguments.add(arg); 
			while (la.kind == 19) {
				Get();
				arg = Expr();
				arguments.add(arg); 
			}
		}
		Expect(13);
		Expect(8);
		stmt = new StmtFunctionCallNode(ident, arguments, t.line, t.col); 
		return stmt;
	}

	TypeNode  Type() {
		TypeNode  type;
		type = null; 
		if (la.kind == 38) {
			Get();
			type = new TypeIntNode(t.line, t.col); 
		} else if (la.kind == 39) {
			Get();
			type = new TypeDoubleNode(t.line, t.col); 
		} else if (la.kind == 40) {
			Get();
			type = new TypeBoolNode(t.line, t.col); 
		} else if (la.kind == 41) {
			Get();
			type = new TypeStringNode(t.line, t.col); 
		} else if (la.kind == 9) {
			Get();
			TypeNode innerType = Type();
			Expect(10);
			type = new TypeListNode(innerType, t.line, t.col); 
		} else SynErr(47);
		return type;
	}

	ExprNode  Expr() {
		ExprNode  expr;
		expr = AndExpr();
		while (la.kind == 20) {
			Get();
			String op = t.val; int line = t.line; int col = t.col; 
			ExprNode right = AndExpr();
			expr = makeBinOpExpr(expr, op, right, line, col); 
		}
		return expr;
	}

	ExprNode  AndExpr() {
		ExprNode  expr;
		expr = EqExpr();
		while (la.kind == 21) {
			Get();
			String op = t.val; int line = t.line; int col = t.col; 
			ExprNode right = EqExpr();
			expr = makeBinOpExpr(expr, op, right, line, col); 
		}
		return expr;
	}

	ExprNode  EqExpr() {
		ExprNode  expr;
		expr = RelExpr();
		while (la.kind == 22 || la.kind == 23) {
			if (la.kind == 22) {
				Get();
			} else {
				Get();
			}
			String op = t.val; int line = t.line; int col = t.col; 
			ExprNode right = RelExpr();
			expr = makeBinOpExpr(expr, op, right, line, col); 
		}
		return expr;
	}

	ExprNode  RelExpr() {
		ExprNode  expr;
		expr = ConcatExpr();
		while (StartOf(4)) {
			if (la.kind == 24) {
				Get();
			} else if (la.kind == 25) {
				Get();
			} else if (la.kind == 26) {
				Get();
			} else {
				Get();
			}
			String op = t.val; int line = t.line; int col = t.col; 
			ExprNode right = ConcatExpr();
			expr = makeBinOpExpr(expr, op, right, line, col); 
		}
		return expr;
	}

	ExprNode  ConcatExpr() {
		ExprNode  expr;
		expr = PlusExpr();
		while (la.kind == 28) {
			Get();
			String op = t.val; int line = t.line; int col = t.col; 
			ExprNode right = PlusExpr();
			expr = makeBinOpExpr(expr, op, right, line, col); 
		}
		return expr;
	}

	ExprNode  PlusExpr() {
		ExprNode  expr;
		expr = MultExpr();
		while (la.kind == 29 || la.kind == 30) {
			if (la.kind == 29) {
				Get();
			} else {
				Get();
			}
			String op = t.val; int line = t.line; int col = t.col; 
			ExprNode right = MultExpr();
			expr = makeBinOpExpr(expr, op, right, line, col); 
		}
		return expr;
	}

	ExprNode  MultExpr() {
		ExprNode  expr;
		expr = NotExpr();
		while (la.kind == 31 || la.kind == 32) {
			if (la.kind == 31) {
				Get();
			} else {
				Get();
			}
			String op = t.val; int line = t.line; int col = t.col; 
			ExprNode right = NotExpr();
			expr = makeBinOpExpr(expr, op, right, line, col); 
		}
		return expr;
	}

	ExprNode  NotExpr() {
		ExprNode  expr;
		List<Character> unaries = new ArrayList(); int line = -1; int col = -1; 
		while (la.kind == 30 || la.kind == 33) {
			if (la.kind == 33) {
				Get();
				unaries.add('!'); 
			} else {
				Get();
				unaries.add('-'); 
			}
			line = t.line; col = t.col; 
		}
		expr = Term();
		expr = makeUnOpExpr(unaries, expr, line, col);  
		return expr;
	}

	ExprNode  Term() {
		ExprNode  expr;
		expr = null; 
		switch (la.kind) {
		case 4: {
			Get();
			String ident = t.val; int line = t.line; int col = t.col; 
			expr = new ExprIdentifierNode(ident, line, col); 
			if (la.kind == 9 || la.kind == 12) {
				if (la.kind == 9) {
					expr = ExprListAccess(ident, line, col);
				} else {
					expr = ExprFuncCall(ident, line, col);
				}
			}
			break;
		}
		case 9: {
			expr = ExprListDeclaration();
			break;
		}
		case 1: {
			Get();
			expr = new ExprIntNode(t.val, t.line, t.col); 
			break;
		}
		case 2: {
			Get();
			expr = new ExprDoubleNode(t.val, t.line, t.col); 
			break;
		}
		case 3: {
			Get();
			expr = new ExprStringNode(t.val, t.line, t.col); 
			break;
		}
		case 34: case 35: {
			if (la.kind == 34) {
				Get();
			} else {
				Get();
			}
			expr = new ExprBoolNode(t.val, t.line, t.col); 
			break;
		}
		case 12: {
			Get();
			expr = Expr();
			Expect(13);
			break;
		}
		default: SynErr(48); break;
		}
		return expr;
	}

	ExprNode  ExprListAccess(String ident, int line, int col) {
		ExprNode  expr;
		List<ExprNode> exprList = new ArrayList<>(); 
		Expect(9);
		expr = Expr();
		exprList.add(expr); 
		Expect(10);
		while (la.kind == 9) {
			Get();
			expr = Expr();
			exprList.add(expr); 
			Expect(10);
		}
		expr = new ExprListAccessNode(ident, exprList, line, col); 
		return expr;
	}

	ExprFunctionCallNode  ExprFuncCall(String ident, int line, int col) {
		ExprFunctionCallNode  funcCall;
		List<ExprNode> exprList = new ArrayList<>(); 
		Expect(12);
		if (StartOf(3)) {
			ExprNode arg = Expr();
			exprList.add(arg); 
			while (la.kind == 19) {
				Get();
				arg = Expr();
				exprList.add(arg); 
			}
		}
		Expect(13);
		funcCall = new ExprFunctionCallNode(ident, exprList, line, col); 
		return funcCall;
	}

	ExprNode  ExprListDeclaration() {
		ExprNode  expr;
		List<ExprNode> exprs = new ArrayList<>(); 
		Expect(9);
		int line = t.line; int col = t.col; 
		if (StartOf(3)) {
			expr = Expr();
			exprs.add(expr); 
		}
		while (la.kind == 19) {
			Get();
			expr = Expr();
			exprs.add(expr); 
		}
		Expect(10);
		expr = new ExprListDeclaration(exprs, line, col); 
		return expr;
	}

	TypeNode  DeclType() {
		TypeNode  type;
		type = null; 
		if (la.kind == 36) {
			Get();
			type = new TypeShapeNode(t.line, t.col); 
		} else if (StartOf(2)) {
			type = Type();
		} else SynErr(49);
		return type;
	}

	TypeNode  FunctionType() {
		TypeNode  type;
		type = null; 
		if (la.kind == 37) {
			Get();
			type = new TypeVoidNode(t.line, t.col); 
		} else if (StartOf(2)) {
			type = Type();
		} else SynErr(50);
		return type;
	}



	public void Parse() {
		la = new Token();
		la.val = "";		
		Get();
		Program();
		Expect(0);

		scanner.buffer.Close();
	}

	private static final boolean[][] set = {
		{_T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_T, _x,_x,_x,_x, _T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x},
		{_x,_x,_x,_x, _T,_x,_x,_x, _x,_T,_x,_T, _x,_x,_x,_x, _T,_x,_T,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_T,_T, _T,_T,_x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_T,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_T,_T, _T,_T,_x,_x},
		{_x,_T,_T,_T, _T,_x,_x,_x, _x,_T,_x,_x, _T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_T,_x, _x,_T,_T,_T, _x,_x,_x,_x, _x,_x,_x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _T,_T,_T,_T, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x}

	};
} // end Parser


class Errors {
	public int count = 0;                                    // number of errors detected
	public java.io.PrintStream errorStream = System.out;     // error messages go to this stream
	public String errMsgFormat = "-- line {0} col {1}: {2}"; // 0=line, 1=column, 2=text
	
	protected void printMsg(int line, int column, String msg) {
		StringBuffer b = new StringBuffer(errMsgFormat);
		int pos = b.indexOf("{0}");
		if (pos >= 0) { b.delete(pos, pos+3); b.insert(pos, line); }
		pos = b.indexOf("{1}");
		if (pos >= 0) { b.delete(pos, pos+3); b.insert(pos, column); }
		pos = b.indexOf("{2}");
		if (pos >= 0) b.replace(pos, pos+3, msg);
		errorStream.println(b.toString());
	}
	
	public void SynErr (int line, int col, int n) {
		String s;
		switch (n) {
			case 0: s = "EOF expected"; break;
			case 1: s = "INT expected"; break;
			case 2: s = "DOUBLE expected"; break;
			case 3: s = "STRING expected"; break;
			case 4: s = "IDENT expected"; break;
			case 5: s = "\"{\" expected"; break;
			case 6: s = "\"}\" expected"; break;
			case 7: s = "\"=\" expected"; break;
			case 8: s = "\";\" expected"; break;
			case 9: s = "\"[\" expected"; break;
			case 10: s = "\"]\" expected"; break;
			case 11: s = "\"if\" expected"; break;
			case 12: s = "\"(\" expected"; break;
			case 13: s = "\")\" expected"; break;
			case 14: s = "\"then\" expected"; break;
			case 15: s = "\"else\" expected"; break;
			case 16: s = "\"while\" expected"; break;
			case 17: s = "\"do\" expected"; break;
			case 18: s = "\"return\" expected"; break;
			case 19: s = "\",\" expected"; break;
			case 20: s = "\"||\" expected"; break;
			case 21: s = "\"&&\" expected"; break;
			case 22: s = "\"==\" expected"; break;
			case 23: s = "\"!=\" expected"; break;
			case 24: s = "\"<=\" expected"; break;
			case 25: s = "\"<\" expected"; break;
			case 26: s = "\">=\" expected"; break;
			case 27: s = "\">\" expected"; break;
			case 28: s = "\"++\" expected"; break;
			case 29: s = "\"+\" expected"; break;
			case 30: s = "\"-\" expected"; break;
			case 31: s = "\"*\" expected"; break;
			case 32: s = "\"/\" expected"; break;
			case 33: s = "\"!\" expected"; break;
			case 34: s = "\"true\" expected"; break;
			case 35: s = "\"false\" expected"; break;
			case 36: s = "\"shape\" expected"; break;
			case 37: s = "\"void\" expected"; break;
			case 38: s = "\"int\" expected"; break;
			case 39: s = "\"double\" expected"; break;
			case 40: s = "\"bool\" expected"; break;
			case 41: s = "\"string\" expected"; break;
			case 42: s = "??? expected"; break;
			case 43: s = "invalid Stmt"; break;
			case 44: s = "invalid Stmt"; break;
			case 45: s = "this symbol not expected in StmtIf"; break;
			case 46: s = "this symbol not expected in StmtWhile"; break;
			case 47: s = "invalid Type"; break;
			case 48: s = "invalid Term"; break;
			case 49: s = "invalid DeclType"; break;
			case 50: s = "invalid FunctionType"; break;
			default: s = "error " + n; break;
		}
		printMsg(line, col, s);
		count++;
	}

	public void SemErr (int line, int col, String s) {	
		printMsg(line, col, s);
		count++;
	}
	
	public void SemErr (String s) {
		errorStream.println(s);
		count++;
	}
	
	public void Warning (int line, int col, String s) {	
		printMsg(line, col, s);
	}
	
	public void Warning (String s) {
		errorStream.println(s);
	}
} // Errors


class FatalError extends RuntimeException {
	public static final long serialVersionUID = 1L;
	public FatalError(String s) { super(s); }
}
